menu:
  Tutorials: /docs/index.html
  Demos: /docs/sandbox/index.html
  API docs: /api/Konva.html
  React: /docs/react/Intro.html
  Vue: /docs/vue/index.html
  ❤️ Support Konva: /docs/donate.html
  Need help?: /docs/support.html
  # Consulting: https://lavrton.com

doc_sidebar:
  Getting Started:
    Intro: index.html
    Overview: overview.html
    Need help?: support.html
    Support Konva: donate.html
    Tools: tools.html
  Shapes:
    Rect: shapes/Rect.html
    Circle: shapes/Circle.html
    Ellipse: shapes/Ellipse.html
    Wedge: shapes/Wedge.html
    Line - Simple Line: shapes/Line_-_Simple_Line.html
    Line - Polygon: shapes/Line_-_Polygon.html
    Line - Spline: shapes/Line_-_Spline.html
    Line - Blob: shapes/Line_-_Blob.html
    Sprite: shapes/Sprite.html
    Image: shapes/Image.html
    Text: shapes/Text.html
    TextPath: shapes/TextPath.html
    Star: shapes/Star.html
    Ring: shapes/Ring.html
    Arc: shapes/Arc.html
    Label: shapes/Label.html
    Path: shapes/Path.html
    RegularPolygon: shapes/RegularPolygon.html
    Arrow: shapes/Arrow.html
    Custom: shapes/Custom.html
  Guides:
    Position vs Offset: posts/Position_vs_Offset.html
    Tainted Canvas Issue: posts/Tainted_Canvas.html
  Styling:
    Fill: styling/Fill.html
    Stroke: styling/Stroke.html
    Opacity: styling/Opacity.html
    Shadow: styling/Shadow.html
    Line Join: styling/Line_Join.html
    Hide and Show: styling/Hide_and_Show.html
    Mouse Cursor Style: styling/Mouse_Cursor.html
    Blend Mode: styling/Blend_Mode.html
    Fill Stroke Order: styling/Fill_Stroke_Order.html
  Events:
    Binding Events: events/Binding_Events.html
    Image Events: events/Image_Events.html
    Mobile Events: events/Mobile_Events.html
    Mobile Scrolling: events/Mobile_Scrolling.html
    Multi Event: events/Multi_Event.html
    Desktop and Mobile: events/Desktop_and_Mobile.html
    Remove Event: events/Remove_Event.html
    Remove by Name: events/Remove_by_Name.html
    Custom Hit Region: events/Custom_Hit_Region.html
    Listen for Events: events/Listen_for_Events.html
    Cancel Propagation: events/Cancel_Propagation.html
    Event Delegation: events/Event_Delegation.html
    Fire Events: events/Fire_Events.html
    Stage Events: events/Stage_Events.html
    Keyboard Events: events/Keyboard_Events.html
  Drag and Drop:
    Drag and Drop: drag_and_drop/Drag_and_Drop.html
    Drag an Image: drag_and_drop/Drag_an_Image.html
    Drag a Group: drag_and_drop/Drag_a_Group.html
    Drag a Line: drag_and_drop/Drag_a_Line.html
    Drag a Stage: drag_and_drop/Drag_a_Stage.html
    Drag Events: drag_and_drop/Drag_Events.html
    Simple Drag Bounds: drag_and_drop/Simple_Drag_Bounds.html
    Complex Drag and Drop: drag_and_drop/Complex_Drag_and_Drop.html
    Drop Events: drag_and_drop/Drop_Events.html
  Select and Transform:
    Basic demo: select_and_transform/Basic_demo.html
    Centered Scaling: select_and_transform/Centered_Scaling.html
    Keep Ratio: select_and_transform/Keep_Ratio.html
    Styling: select_and_transform/Transformer_Styling.html
    Transform Events: select_and_transform/Transform_Events.html
    Resize Limits: select_and_transform/Resize_Limits.html
    Rotation Snaps: select_and_transform/Rotation_Snaps.html
    Resize Snaps: select_and_transform/Resize_Snaps.html
    Stop Transform: select_and_transform/Stop_Transform.html
    Force Update: select_and_transform/Force_Update.html
    Text Resizing: select_and_transform/Resize_Text.html
    Ignore Stroke: select_and_transform/Ignore_Stroke_On_Transform.html
  Clipping:
    Simple Clip: clipping/Clipping_Regions.html
    Complex Clip: clipping/Clipping_Function.html
  Groups, Layers and Ordering:
    Groups: groups_and_layers/Groups.html
    Layering: groups_and_layers/Layering.html
    Change Containers: groups_and_layers/Change_Containers.html
    zIndex: groups_and_layers/zIndex.html
  Filters:
    Blur: filters/Blur.html
    Brighten: filters/Brighten.html
    Contrast: filters/Contrast.html
    Emboss: filters/Emboss.html
    Enhance: filters/Enhance.html
    Grayscale: filters/Grayscale.html
    HSL: filters/HSL.html
    HSV: filters/HSV.html
    RGB: filters/RGB.html
    Invert: filters/Invert.html
    Kaleidoscope: filters/Kaleidoscope.html
    Mask: filters/Mask.html
    Noise: filters/Noise.html
    Pixelate: filters/Pixelate.html
    Custom Filter: filters/Custom_Filter.html
    Multiple Filters: filters/Multiple_Filters.html
  Tweens:
    Linear Easing: tweens/Linear_Easing.html
    Common Easings: tweens/Common_Easings.html
    All Easings: tweens/All_Easings.html
    Finish Event: tweens/Finish_Event.html
    All Controls: tweens/All_Controls.html
    Tween Filter: tweens/Tween_Filter.html
    Complex Tweening: tweens/Complex_Tweening.html
  Animations:
    Create an Animation: animations/Create_an_Animation.html
    Moving: animations/Moving.html
    Rotation: animations/Rotation.html
    Scaling: animations/Scaling.html
    Stop Animation: animations/Stop_Animation.html
  Selectors:
    Select by id: selectors/Select_by_id.html
    Select by Type: selectors/Select_by_Type.html
    Select by Name: selectors/Select_by_Name.html
  Data & Serialization & Export:
    Serialize a Stage: data_and_serialization/Serialize_a_Stage.html
    Simple Load: data_and_serialization/Simple_Load.html
    Complex Load: data_and_serialization/Complex_Load.html
    JSON Best Practices: data_and_serialization/Best_Practices.html
    Stage Data URL: data_and_serialization/Stage_Data_URL.html
    Export to HD Image: data_and_serialization/High-Quality-Export.html
  Performance:
    All tips: performance/All_Performance_Tips.html
    Layer Management: performance/Layer_Management.html
    Batch Draw: performance/Batch_Draw.html
    Shape Caching: performance/Shape_Caching.html
    Optimize Animation: performance/Optimize_Animation.html
    Optimize Strokes: performance/Optimize_Strokes.html
    Shape Redraw: performance/Shape_Redraw.html
    Disable Perfect Drawing: performance/Disable_Perfect_Draw.html
    Listening False: performance/Listening_False.html
    Avoid Memory Leaks: performance/Avoid_Memory_Leaks.html

demo_sidebar:
  CAD Systems:
    Canvas Editor:
      - polotno.jpg
      - sandbox/Canvas_Editor.html
    Simple Window Frame:
      - simple-window.png
      - sandbox/Simple_Window_Frame.html
    Window Frame Designer:
      - window.png
      - sandbox/Window_Frame_Designer.html
    Seats Reservation:
      - seats-reservation.jpg
      - sandbox/Seats_Reservation.html
    Drawing Labels on Image:
      - annotate.jpg
      - sandbox/Image_Labeling.html
    Interactive Building Map:
      - building_map-min.png
      - sandbox/Interactive_Building_Map.html

  Games and Apps:
    Wheel of Fortune:
      - wheel-of-fortune-min.png
      - sandbox/Wheel_of_Fortune.html
    Free Drawing:
      - free-drawing-min.png
      - sandbox/Free_Drawing.html
    Animals on the Beach Game:
      - animals-min.png
      - sandbox/Animals_on_the_Beach_Game.html
    Planets Image Map:
      - planet-min.png
      - sandbox/Planets_Image_Map.html
    Physics Simulator:
      - simulator-min.png
      - sandbox/Physics_Simulator.html

  Common use cases:
    Editable Text:
      - editable_text-min.png
      - sandbox/Editable_Text.html
    Rich Text rendering:
      - rich-text.jpg
      - sandbox/Rich_Text.html
    Canvas Scrolling:
      - scroll.png
      - sandbox/Canvas_Scrolling.html
    Gif Animation:
      - gif.jpg
      - sandbox/GIF_On_Canvas.html
    Display Video:
      - video.jpg
      - sandbox/Video_On_Canvas.html
    SVG on Canvas:
      - svg_on_canvas.jpg
      - sandbox/SVG_On_Canvas.html
    Canvas Background:
      - canvas-background.jpg
      - sandbox/Canvas_Background.html
    Transparent Group:
      - transparent-group.jpg
      - sandbox/Transparent_Group.html
    Mirror/Flip Shape:
      - mirror-shape.jpg
      - sandbox/Mirror_Canvas_Shape.html
    Canvas to PDF:
      - pdf.jpg
      - sandbox/Canvas_to_PDF.html
    Custom Font:
      - custom-font.png
      - sandbox/Custom_Font.html
    Relative Pointer Position:
      - pointer.png
      - sandbox/Relative_Pointer_Position.html
    Drop DOM Element:
      - drop.png
      - sandbox/Drop_DOM_Element.html
    Objects Snapping:
      - objects_snapping.png
      - sandbox/Objects_Snapping.html
    Zoom Relative To Pointer:
      - relative_zoom-min.png
      - sandbox/Zooming_Relative_To_Pointer.html
    Context Menu:
      - context.jpg
      - sandbox/Canvas_Context_Menu.html
    Image Scale To Fit:
      - fit-image.jpg
      - sandbox/Scale_Image_To_Fit.html
    Limit Resize and Drag:
      - resize-limit.jpg
      - sandbox/Limited_Drag_And_Resize.html
  Performance tests:
    Drag and Drop Stress Test:
      - drag_stress-min.png
      - sandbox/Drag_and_Drop_Stress_Test.html
    Animation Stress Test:
      - animation_stress-min.png
      - sandbox/Animation_Stress_Test.html
    Bunnies Stress Test:
      - bunnies.jpg
      - sandbox/Jumping_Bunnies.html
    10000 Shapes with Tooltip:
      - tooltip_stress-min.png
      - sandbox/10000_Shapes_with_Tooltip.html
    20000 Nodes:
      - 2000_nodes-min.png
      - sandbox/20000_Nodes.html
    Resizing Stress Test:
      - resize_stress.jpg
      - sandbox/Resizing_Stress_Test.html
    Quantum Squiggle:
      - squiggle-min.png
      - sandbox/Quantum_Squiggle.html
  Other random demos:
    Web Worker:
      - offscreen.jpg
      - sandbox/Web_Worker.html
    Star Spinner:
      - spinner-min.png
      - sandbox/Star_Spinner.html
    Connected Objects:
      - connected-objects.png
      - sandbox/Connected_Objects.html
    Manual Image Resize:
      - image-resize-min.png
      - sandbox/Image_Resize.html
    Stage Preview:
      - preview.jpg
      - sandbox/Stage_Preview.html
    Modify Curves with Anchor Points:
      - modify-line-min.png
      - sandbox/Modify_Curves_with_Anchor_Points.html
    Image Border:
      - border.jpg
      - sandbox/Image_Border.html
    Collision Detection:
      - collision-min.png
      - sandbox/Collision_Detection.html
    Elastic Stars:
      - stars-min.png
      - sandbox/Elastic_Stars.html
    Shape Tango:
      - tango-min.png
      - sandbox/Shape_Tango.html
    Image Border Highlighting:
      - border-min.png
      - sandbox/Image_Border_Highlighting.html
    Zoom Layer On hover:
      - hover_zoom-min.png
      - sandbox/Zoom_Layer_On_hover.html
    Responsive Canvas Stage:
      - responsive-min.png
      - sandbox/Responsive_Canvas.html
    Touch Gestures:
      - gestures.jpg
      - sandbox/Gestures.html
    Multi-touch Scale Shape:
      - multitouch-min.png
      - sandbox/Multi-touch_Scale_Shape.html
    Multi-touch Scale Stage:
      - multitouch-min.png
      - sandbox/Multi-touch_Scale_Stage.html
    Modify Shape Color on Click:
      - color_click-min.png
      - sandbox/Modify_Shape_Color_on_Click.html
    Expand Images on Hover:
      - hover_expand-min.png
      - sandbox/Expand_Images_on_Hover.html
    Shape Tooltip:
      - shape_tooltip-min.png
      - sandbox/Shape_Tooltips.html
    Drag and Drop Multiple Shapes:
      - drag_multiple-min.png
      - sandbox/Drag_and_Drop_Multiple_Shapes.html

    # Stage Preview: sandbox/Stage_Peview.html
    # Editable Text: sandbox/Editable_Text.html
    # Rich Text: sandbox/Rich_Text.html
    # Simple Window Frame: sandbox/Simple_Window_Frame.html
    # Window Frame Designer: sandbox/Window_Frame_Designer.html
    # Drawing Labels on Image: sandbox/Image_Labeling.html
    # Collision Detection: sandbox/Collision_Detection.html
    # Zoom Layer On hover: sandbox/Zoom_Layer_On_hover.html
    # Responsive Canvas Stage: sandbox/Responsive_Canvas.html
    # Canvas Scrolling: sandbox/Canvas_Scrolling.html
    # Connected Objects: sandbox/Connected_Objects.html
    # Relative Zoom: sandbox/Zooming_Relative_To_Pointer.html
    # Wheel of Fortune: sandbox/Wheel_of_Fortune.html
    # Quantum Squiggle: sandbox/Quantum_Squiggle.html
    # 20000 Nodes: sandbox/20000_Nodes.html
    # Elastic Stars: sandbox/Elastic_Stars.html
    # Objects Snapping: sandbox/Objects_Snapping.html
    # Shape Tango: sandbox/Shape_Tango.html
    # Multi-touch Scale Shape: sandbox/Multi-touch_Scale_Shape.html
    # Multi-touch Scale Stage: sandbox/Multi-touch_Scale_Stage.html
    # Interactive Building Map: sandbox/Interactive_Building_Map.html
    # Modify Curves with Anchor Points: sandbox/Modify_Curves_with_Anchor_Points.html
    # Drag and Drop Stress Test: sandbox/Drag_and_Drop_Stress_Test.html
    # Animals on the Beach Game: sandbox/Animals_on_the_Beach_Game.html
    # Animation Stress Test: sandbox/Animation_Stress_Test.html
    # Bunnies Stress Test: sandbox/Jumping_Bunnies.html
    # 10000 Shapes with Tooltips: sandbox/10000_Shapes_with_Tooltip.html
    # Modify Shape Color on Click: sandbox/Modify_Shape_Color_on_Click.html
    # Physics Simulator: sandbox/Physics_Simulator.html
    # Expand Images on Hover: sandbox/Expand_Images_on_Hover.html
    # Planets Image Map: sandbox/Planets_Image_Map.html
    # Image Resize: sandbox/Image_Resize.html
    # Shape Tooltips: sandbox/Shape_Tooltips.html
    # Star Spinner: sandbox/Star_Spinner.html
    # Drag and Drop Multiple Shapes: sandbox/Drag_and_Drop_Multiple_Shapes.html
    # Image Border Highlighting: sandbox/Image_Border_Highlighting.html
    # GIF Animation: sandbox/GIF_On_Canvas.html
    # Relative Pointer Position: sandbox/Relative_Pointer_Position.html
    # Drop DOM Element: sandbox/Drop_DOM_Element.html
    # Custom Font: sandbox/Custom_Font.html
    # Video On Canvas: sandbox/Video_On_Canvas.html
    # Native Context Access: sandbox/Native_Context_Access.html
    # SVG On Canvas: sandbox/SVG_On_Canvas.html
    # Seats Reservation: sandbox/Seats_Reservation.html
    # Touch Gestures: sandbox/Gestures.html

react_sidebar:
  Docs:
    Intro: react/Intro.html
    Overview: react/index.html
    Basic shapes: react/Shapes.html
    Custom shape: react/Custom_Shape.html
    Events: react/Events.html
    Images: react/Images.html
    Filters: react/Filters.html
    Drag and Drop: react/Drag_And_Drop.html
    Refs and Konva Nodes: react/Access_Konva_Nodes.html
    Transformer: react/Transformer.html
    Simple Animations: react/Simple_Animations.html
    Complex Animations: react/Complex_Animations.html
  Utils:
    DOM Portal: react/DOM_Portal.html
    Canvas Portal: react/Canvas_Portal.html
  Demos:
    Export into Image: react/Canvas_Export.html
    Undo/Redo: react/Undo-Redo.html
    Changing zIndex: react/zIndex.html
    Drop DOM Image Into Canvas: react/Drop_Image.html
    Free Drawing: react/Free_Drawing.html

vue_sidebar:
  Getting Started with Vue:
    Intro: vue/index.html
    Basic shapes: vue/Shapes.html
    Custom shape: vue/Custom_Shape.html
  Vue demos:
    Events: vue/Events.html
    Images: vue/Images.html
    Filters: vue/Filters.html
    Save/Load: vue/Save-Load.html
    Drag and Drop: vue/Drag_And_Drop.html
    Transformer: vue/Transformer.html
    Simple Animations: vue/Simple_Animations.html
    Cache: vue/Cache.html

fb_admins:
twitter: lavrton
github: konvajs/konva
