menu:
  教程: /docs/
  示例: /docs/sandbox
  API: /api/Konva.html
  React: /docs/react
  Vue: /docs/vue
  支持 Konva: /docs/donate.html
  帮助: /docs/support.html
  # Consulting: https://lavrton.com

doc_sidebar:
  快速上手:
    简介: index.html
    基础: overview.html
    帮助: support.html
    支持 Konva: donate.html
    工具: tools.html
  图形:
    Rect 矩形: shapes/Rect.html
    Circle 圆形: shapes/Circle.html
    Ellipse 椭圆: shapes/Ellipse.html
    Wedge 扇形: shapes/Wedge.html
    Line - 简单线条: shapes/Line_-_Simple_Line.html
    Line - 多边形: shapes/Line_-_Polygon.html
    Line - 样条曲线: shapes/Line_-_Spline.html
    Line - 不规则图形: shapes/Line_-_Blob.html
    Sprite 精灵图: shapes/Sprite.html
    Image 图片: shapes/Image.html
    Text 文字: shapes/Text.html
    TextPath 路径文字: shapes/TextPath.html
    Star 星形: shapes/Star.html
    Ring 环形: shapes/Ring.html
    Arc 弧形: shapes/Arc.html
    Label 标签: shapes/Label.html
    Path 路径: shapes/Path.html
    RegularPolygon 等边多边形: shapes/RegularPolygon.html
    Arrow 箭头: shapes/Arrow.html
    Custom 自定义图形: shapes/Custom.html
  指南:
    定位 vs 偏移: posts/Position_vs_Offset.html
  样式:
    填充: styling/Fill.html
    笔画: styling/Stroke.html
    透明度: styling/Opacity.html
    阴影: styling/Shadow.html
    边角: styling/Line_Join.html
    显示和隐藏图形: styling/Hide_and_Show.html
    鼠标样式: styling/Mouse_Cursor.html
    混合模式: styling/Blend_Mode.html
  事件:
    事件绑定: events/Binding_Events.html
    图片事件: events/Image_Events.html
    移动端事件: events/Mobile_Events.html
    移动端滚动: events/Mobile_Scrolling.html
    多重事件: events/Multi_Event.html
    桌面端和移动端: events/Desktop_and_Mobile.html
    移除: events/Remove_Event.html
    通过名称移除: events/Remove_by_Name.html
    自定义响应区域: events/Custom_Hit_Region.html
    监听事件: events/Listen_for_Events.html
    停止传播: events/Cancel_Propagation.html
    事件委托: events/Event_Delegation.html
    触发事件: events/Fire_Events.html
    舞台事件: events/Stage_Events.html
    键盘事件: events/Keyboard_Events.html
  拖放:
    拖放: drag_and_drop/Drag_and_Drop.html
    拖动图片: drag_and_drop/Drag_an_Image.html
    拖动组: drag_and_drop/Drag_a_Group.html
    拖动线条: drag_and_drop/Drag_a_Line.html
    拖动舞台: drag_and_drop/Drag_a_Stage.html
    拖动事件: drag_and_drop/Drag_Events.html
    限制拖动区域: drag_and_drop/Simple_Drag_Bounds.html
    复杂拖放: drag_and_drop/Complex_Drag_and_Drop.html
    释放事件: drag_and_drop/Drop_Events.html
  选择和变换图形:
    基础示例: select_and_transform/Basic_demo.html
    基于中心缩放: select_and_transform/Centered_Scaling.html
    保持宽高比: select_and_transform/Keep_Ratio.html
    修改样式: select_and_transform/Transformer_Styling.html
    图形变换事件: select_and_transform/Transform_Events.html
    缩放限制: select_and_transform/Resize_Limits.html
    旋转吸附: select_and_transform/Rotation_Snaps.html
    停止变换: select_and_transform/Stop_Transform.html
    强制更新: select_and_transform/Force_Update.html
  裁剪:
    简单裁剪: clipping/Clipping_Regions.html
    复杂裁剪: clipping/Clipping_Function.html
  组、图层和层级:
    组: groups_and_layers/Groups.html
    布局: groups_and_layers/Layering.html
    更换容器: groups_and_layers/Change_Containers.html
    zIndex: groups_and_layers/zIndex.html
  滤镜:
    Blur 模糊: filters/Blur.html
    Brighten 亮度: filters/Brighten.html
    Contrast 对比度: filters/Contrast.html
    Emboss 浮雕: filters/Emboss.html
    Enhance 增强反差: filters/Enhance.html
    Grayscale 灰度: filters/Grayscale.html
    HSL: filters/HSL.html
    HSV: filters/HSV.html
    RGB: filters/RGB.html
    Invert 反向: filters/Invert.html
    Kaleidoscope 万花筒: filters/Kaleidoscope.html
    Mask 遮罩: filters/Mask.html
    Noise 噪声: filters/Noise.html
    Pixelate 像素化: filters/Pixelate.html
    自定义滤镜: filters/Custom_Filter.html
    多重滤镜: filters/Multiple_Filters.html
  补间动画:
    线性 Easing: tweens/Linear_Easing.html
    自定义 Easings: tweens/Common_Easings.html
    全部 Easings: tweens/All_Easings.html
    动画完成事件: tweens/Finish_Event.html
    控制器: tweens/All_Controls.html
    补间滤镜: tweens/Tween_Filter.html
    复杂补间: tweens/Complex_Tweening.html
  动画:
    创建动画: animations/Create_an_Animation.html
    移动: animations/Moving.html
    旋转: animations/Rotation.html
    缩放: animations/Scaling.html
    停止动画: animations/Stop_Animation.html
  选择器:
    通过  id: selectors/Select_by_id.html
    通过 type: selectors/Select_by_Type.html
    通过 name: selectors/Select_by_Name.html
  数据 & 序列化 & 导出:
    序列化舞台数据: data_and_serialization/Serialize_a_Stage.html
    简单导入: data_and_serialization/Simple_Load.html
    复杂导入: data_and_serialization/Complex_Load.html
    JSON最佳实践: data_and_serialization/Best_Practices.html
    舞台 Data URL: data_and_serialization/Stage_Data_URL.html
    到处高分辨率图片: data_and_serialization/High-Quality-Export.html
  性能优化:
    技巧: performance/All_Performance_Tips.html
    图层管理: performance/Layer_Management.html
    批量绘制: performance/Batch_Draw.html
    图形缓存: performance/Shape_Caching.html
    动画优化: performance/Optimize_Animation.html
    笔画优化: performance/Optimize_Strokes.html
    图形重绘: performance/Shape_Redraw.html
    关闭 Perfect Drawing: performance/Disable_Perfect_Draw.html
    禁用事件监听: performance/Listening_False.html
    防止内存溢出: performance/Avoid_Memory_Leaks.html

demo_sidebar:
  Games and Apps:
    Wheel of Fortune:
      - wheel-of-fortune-min.png
      - sandbox/Wheel_of_Fortune.html
    Free Drawing:
      - free-drawing-min.png
      - sandbox/Free_Drawing.html
    Animals on the Beach Game:
      - animals-min.png
      - sandbox/Animals_on_the_Beach_Game.html
    Planets Image Map:
      - planet-min.png
      - sandbox/Planets_Image_Map.html
    Physics Simulator:
      - simulator-min.png
      - sandbox/Physics_Simulator.html
  CAD Systems:
    Simple Window Frame:
      - simple-window.png
      - sandbox/Simple_Window_Frame.html
    Window Frame Designer:
      - window.png
      - sandbox/Window_Frame_Designer.html
    Seats Reservation:
      - seats-reservation.jpg
      - sandbox/Seats_Reservation.html
    Drawing Labels on Image:
      - annotate.jpg
      - sandbox/Image_Labeling.html
    Interactive Building Map:
      - building_map-min.png
      - sandbox/Interactive_Building_Map.html
  Common use cases:
    Editable Text:
      - editable_text-min.png
      - sandbox/Editable_Text.html
    Rich Text rendering:
      - rich-text.jpg
      - sandbox/Rich_Text.html
    Canvas Scrolling:
      - scroll.png
      - sandbox/Canvas_Scrolling.html
    Gif Animation:
      - gif.jpg
      - sandbox/GIF_On_Canvas.html
    Display Video:
      - video.jpg
      - sandbox/Video_On_Canvas.html
    SVG on Canvas:
      - svg_on_canvas.jpg
      - sandbox/SVG_On_Canvas.html
    Custom Font:
      - custom-font.png
      - sandbox/Custom_Font.html
    Relative Pointer Position:
      - pointer.png
      - sandbox/Relative_Pointer_Position.html
    Drop DOM Element:
      - drop.png
      - sandbox/Drop_DOM_Element.html
    Objects Snapping:
      - objects_snapping.png
      - sandbox/Objects_Snapping.html
    Zoom Relative To Pointer:
      - relative_zoom-min.png
      - sandbox/Zooming_Relative_To_Pointer.html
    Context Menu:
      - context.jpg
      - sandbox/Canvas_Context_Menu.html
  Performance tests:
    Drag and Drop Stress Test:
      - drag_stress-min.png
      - sandbox/Drag_and_Drop_Stress_Test.html
    Animation Stress Test:
      - animation_stress-min.png
      - sandbox/Animation_Stress_Test.html
    Bunnies Stress Test:
      - bunnies.jpg
      - sandbox/Jumping_Bunnies.html
    10000 Shapes with Tooltip:
      - tooltip_stress-min.png
      - sandbox/10000_Shapes_with_Tooltip.html
    20000 Nodes:
      - 2000_nodes-min.png
      - sandbox/20000_Nodes.html
    Quantum Squiggle:
      - squiggle-min.png
      - sandbox/Quantum_Squiggle.html
  Other random demos:
    Star Spinner:
      - spinner-min.png
      - sandbox/Star_Spinner.html
    Connected Objects:
      - connected-objects.png
      - sandbox/Connected_Objects.html
    Manual Image Resize:
      - image-resize-min.png
      - sandbox/Image_Resize.html
    Stage Preview:
      - preview.jpg
      - sandbox/Stage_Preview.html
    Modify Curves with Anchor Points:
      - modify-line-min.png
      - sandbox/Modify_Curves_with_Anchor_Points.html
    Collision Detection:
      - collision-min.png
      - sandbox/Collision_Detection.html
    Elastic Stars:
      - stars-min.png
      - sandbox/Elastic_Stars.html
    Shape Tango:
      - tango-min.png
      - sandbox/Shape_Tango.html
    Image Border Highlighting:
      - border-min.png
      - sandbox/Image_Border_Highlighting.html
    Zoom Layer On hover:
      - hover_zoom-min.png
      - sandbox/Zoom_Layer_On_hover.html
    Responsive Canvas Stage:
      - responsive-min.png
      - sandbox/Responsive_Canvas.html
    Touch Gestures:
      - gestures.jpg
      - sandbox/Gestures.html
    Multi-touch Scale Shape:
      - multitouch-min.png
      - sandbox/Multi-touch_Scale_Shape.html
    Multi-touch Scale Stage:
      - multitouch-min.png
      - sandbox/Multi-touch_Scale_Stage.html
    Modify Shape Color on Click:
      - color_click-min.png
      - sandbox/Modify_Shape_Color_on_Click.html
    Expand Images on Hover:
      - hover_expand-min.png
      - sandbox/Expand_Images_on_Hover.html
    Shape Tooltip:
      - shape_tooltip-min.png
      - sandbox/Shape_Tooltips.html
    Drag and Drop Multiple Shapes:
      - drag_multiple-min.png
      - sandbox/Drag_and_Drop_Multiple_Shapes.html

    # Stage Preview: sandbox/Stage_Peview.html
    # Editable Text: sandbox/Editable_Text.html
    # Rich Text: sandbox/Rich_Text.html
    # Simple Window Frame: sandbox/Simple_Window_Frame.html
    # Window Frame Designer: sandbox/Window_Frame_Designer.html
    # Drawing Labels on Image: sandbox/Image_Labeling.html
    # Collision Detection: sandbox/Collision_Detection.html
    # Zoom Layer On hover: sandbox/Zoom_Layer_On_hover.html
    # Responsive Canvas Stage: sandbox/Responsive_Canvas.html
    # Canvas Scrolling: sandbox/Canvas_Scrolling.html
    # Connected Objects: sandbox/Connected_Objects.html
    # Relative Zoom: sandbox/Zooming_Relative_To_Pointer.html
    # Wheel of Fortune: sandbox/Wheel_of_Fortune.html
    # Quantum Squiggle: sandbox/Quantum_Squiggle.html
    # 20000 Nodes: sandbox/20000_Nodes.html
    # Elastic Stars: sandbox/Elastic_Stars.html
    # Objects Snapping: sandbox/Objects_Snapping.html
    # Shape Tango: sandbox/Shape_Tango.html
    # Multi-touch Scale Shape: sandbox/Multi-touch_Scale_Shape.html
    # Multi-touch Scale Stage: sandbox/Multi-touch_Scale_Stage.html
    # Interactive Building Map: sandbox/Interactive_Building_Map.html
    # Modify Curves with Anchor Points: sandbox/Modify_Curves_with_Anchor_Points.html
    # Drag and Drop Stress Test: sandbox/Drag_and_Drop_Stress_Test.html
    # Animals on the Beach Game: sandbox/Animals_on_the_Beach_Game.html
    # Animation Stress Test: sandbox/Animation_Stress_Test.html
    # Bunnies Stress Test: sandbox/Jumping_Bunnies.html
    # 10000 Shapes with Tooltips: sandbox/10000_Shapes_with_Tooltip.html
    # Modify Shape Color on Click: sandbox/Modify_Shape_Color_on_Click.html
    # Physics Simulator: sandbox/Physics_Simulator.html
    # Expand Images on Hover: sandbox/Expand_Images_on_Hover.html
    # Planets Image Map: sandbox/Planets_Image_Map.html
    # Image Resize: sandbox/Image_Resize.html
    # Shape Tooltips: sandbox/Shape_Tooltips.html
    # Star Spinner: sandbox/Star_Spinner.html
    # Drag and Drop Multiple Shapes: sandbox/Drag_and_Drop_Multiple_Shapes.html
    # Image Border Highlighting: sandbox/Image_Border_Highlighting.html
    # GIF Animation: sandbox/GIF_On_Canvas.html
    # Relative Pointer Position: sandbox/Relative_Pointer_Position.html
    # Drop DOM Element: sandbox/Drop_DOM_Element.html
    # Custom Font: sandbox/Custom_Font.html
    # Video On Canvas: sandbox/Video_On_Canvas.html
    # Native Context Access: sandbox/Native_Context_Access.html
    # SVG On Canvas: sandbox/SVG_On_Canvas.html
    # Seats Reservation: sandbox/Seats_Reservation.html
    # Touch Gestures: sandbox/Gestures.html

react_sidebar:
  Getting Started with React:
    Intro: react/index.html
    Basic shapes: react/Shapes.html
    Custom shape: react/Custom_Shape.html
  React demos:
    Events: react/Events.html
    Images: react/Images.html
    Filters: react/Filters.html
    Drag and Drop: react/Drag_And_Drop.html
    Transformer: react/Transformer.html
    Simple Animations: react/Simple_Animations.html
    Complex Animations: react/Complex_Animations.html
    DOM Portals: react/DOM_Portal.html
    Undo/Redo: react/Undo-Redo.html
    Changing zIndex: react/zIndex.html

vue_sidebar:
  Getting Started with Vue:
    Intro: vue/index.html
    Basic shapes: vue/Shapes.html
    Custom shape: vue/Custom_Shape.html
  Vue demos:
    Events: vue/Events.html
    Images: vue/Images.html
    Filters: vue/Filters.html
    Save/Load: vue/Save-Load.html
    Drag and Drop: vue/Drag_And_Drop.html
    Transformer: vue/Transformer.html
    Simple Animations: vue/Simple_Animations.html
    Cache: vue/Cache.html

google_analytics: UA-54202824-2
fb_admins:
swiftype_key: rRaQRFqx1DcWDDysdpg_
twitter: lavrton
github: konvajs/konva
