menu:
  Docs: /docs/
  API: /api/Konva.html
  Support: /docs/support.html

doc_sidebar:
  Getting Started:
    Intro: index.html
    Overview: overview.html
    Support: support.html
    Tools : tools.html
  Shapes:
    Rect : shapes/Rect.html
    Circle : shapes/Circle.html
    Ellipse : shapes/Ellipse.html
    Wedge : shapes/Wedge.html
    Line - Simple Line : shapes/Line_-_Simple_Line.html
    Line - Polygon : shapes/Line_-_Polygon.html
    Line - Spline : shapes/Line_-_Spline.html
    Line - Blob : shapes/Line_-_Blob.html
    Sprite : shapes/Sprite.html
    Image : shapes/Image.html
    Text : shapes/Text.html
    TextPath : shapes/TextPath.html
    Star : shapes/Star.html
    Label : shapes/Label.html
    Path : shapes/Path.html
    RegularPolygon : shapes/RegularPolygon.html
    Arrow : shapes/Arrow.html
    Custom : shapes/Custom.html
  Styling:
    Fill : styling/Fill.html
    Stroke : styling/Stroke.html
    Opacity : styling/Opacity.html
    Shadow : styling/Shadow.html
    Line Join : styling/Line_Join.html
    Hide and Show : styling/Hide_and_Show.html
  Events:
    Binding Events : events/Binding_Events.html
    Image Events : events/Image_Events.html
    Mobile Events : events/Mobile_Events.html
    Multi Event : events/Multi_Event.html
    Desktop and Mobile : events/Desktop_and_Mobile.html
    Remove Event : events/Remove_Event.html
    Remove by Name : events/Remove_by_Name.html
    Custom Hit Region : events/Custom_Hit_Region.html
    Listen for Events : events/Listen_for_Events.html
    Cancel Propagation : events/Cancel_Propagation.html
    Event Delegation : events/Event_Delegation.html
    Fire Events : events/Fire_Events.html
  Drag and Drop:
    Drag and Drop : drag_and_drop/Drag_and_Drop.html
    Drag an Image : drag_and_drop/Drag_an_Image.html
    Drag a Group : drag_and_drop/Drag_a_Group.html
    Drag a Line : drag_and_drop/Drag_a_Line.html
    Drag a Stage : drag_and_drop/Drag_a_Stage.html
    Drag Events : drag_and_drop/Drag_Events.html
    Simple Drag Bounds : drag_and_drop/Simple_Drag_Bounds.html
    Complex Drag and Drop : drag_and_drop/Complex_Drag_and_Drop.html
    Drop Events : drag_and_drop/Drop_Events.html
  Groups and Layers:
    Groups : groups_and_layers/Groups.html
    Layering : groups_and_layers/Layering.html
    Change Containers : groups_and_layers/Change_Containers.html
    Clipping Regions : groups_and_layers/Clipping_Regions.html
  Filters:
    Invert : filters/Invert.html
    Grayscale : filters/Grayscale.html
    Brighten : filters/Brighten.html
    Kaleidoscope : filters/Kaleidoscope.html
    Blur : filters/Blur.html
    Multiple Filters : filters/Multiple_Filters.html
  Tweens:
    Linear Easing : tweens/Linear_Easing.html
    Common Easings : tweens/Common_Easings.html
    All Easings : tweens/All_Easings.html
    Finish Event : tweens/Finish_Event.html
    All Controls : tweens/All_Controls.html
    Tween Filter : tweens/Tween_Filter.html
    Complex Tweening : tweens/Complex_Tweening.html
  Animations:
    Create an Animation : animations/Create_an_Animation.html
    Moving : animations/Moving.html
    Rotation  : animations/Rotation.html
    Scaling : animations/Scaling.html
    Stop Animation : animations/Stop_Animation.html
  Selectors:
    Select by id : selectors/Select_by_id.html
    Select by Type : selectors/Select_by_Type.html
    Select by Name : selectors/Select_by_Name.html
  Data & Serialization:
    Serialize a Stage : data_&_serialization/Serialize_a_Stage.html
    Simple Load : data_&_serialization/Simple_Load.html
    Complex Load : data_&_serialization/Complex_Load.html
    Stage Data URL : data_&_serialization/Stage_Data_URL.html
  Performance:
    Layer Management : performance/Layer_Management.html
    Batch Draw : performance/Batch_Draw.html
    Shape Caching : performance/Shape_Caching.html
    Optimize Animation : performance/Optimize_Animation.html
    Optimize Strokes : performance/Optimize_Strokes.html
    Shape Redraw : performance/Shape_Redraw.html
    Disable Perfect Drawing : performance/Disable_Perfect_Draw.html
    Listening False : performance/Listening_False.html
    Avoid Memory Leaks : performance/Avoid_Memory_Leaks.html
    All tips : performance/All_Performance_Tips.html
  Sandbox:
    Free Drawing : sandbox/Free_Drawing.html
    Zoom Layer On hover : sandbox/Zoom_Layer_On_hover.html
    Wheel of Fortune : sandbox/Wheel_of_Fortune.html
    Quantum Squiggle : sandbox/Quantum_Squiggle.html
    20000 Nodes : sandbox/20000_Nodes.html
    Elastic Stars : sandbox/Elastic_Stars.html
    Shape Tango : sandbox/Shape_Tango.html
    Multi-touch Scale Shape : sandbox/Multi-touch_Scale_Shape.html
    Multi-touch Scale Stage : sandbox/Multi-touch_Scale_Stage.html
    Interactive Building Map : sandbox/Interactive_Building_Map.html
    Modify Curves with Anchor Points : sandbox/Modify_Curves_with_Anchor_Points.html
    Drag and Drop Stress Test : sandbox/Drag_and_Drop_Stress_Test.html
    Animals on the Beach Game : sandbox/Animals_on_the_Beach_Game.html
    Animation Stress Test : sandbox/Animation_Stress_Test.html
    10000 Shapes with Tooltips : sandbox/10000_Shapes_with_Tooltip.html
    Modify Shape Color on Click : sandbox/Modify_Shape_Color_on_Click.html
    Physics Simulator : sandbox/Physics_Simulator.html
    Expand Images on Hover : sandbox/Expand_Images_on_Hover.html
    Planets Image Map : sandbox/Planets_Image_Map.html
    Image Resize : sandbox/Image_Resize.html
    Shape Tooltips : sandbox/Shape_Tooltips.html
    Star Spiner : sandbox/Star_Spiner.html
    Drag and Drop Multiple Shapes : sandbox/Drag_and_Drop_Multiple_Shapes.html
    Image Border Highlighting : sandbox/Image_Border_Highlighting.html

google_analytics: UA-54202824-2
fb_admins:
swiftype_key: rRaQRFqx1DcWDDysdpg_
twitter: lavrton
github: konvajs/konva
